### ISSUE TITLE
link.rs file broken for 32 bit systems

### ISSUE THREAD

**Issue by drevilt** [PistonDevelopers/dyon#383]
when using a 32-bit ( arm ) system you get:

```
error[E0512]: transmute called with differently sized types: usize (32 bits) to f64 (64 bits)
  --> /.../dyon-0.9.0/src/link.rs:40:21
   |
40 |                     transmute::<usize, f64>(self.data[k])
   |                     ^^^^^^^^^^^^^^^^^^^^^^^

error[E0512]: transmute called with differently sized types: f64 (64 bits) to usize (32 bits)
  --> /.../dyon-0.9.0/src/link.rs:74:41
   |
74 |                 self.data[k] = unsafe { transmute::<f64, usize>(val) };
   |                                         ^^^^^^^^^^^^^^^^^^^^^^^
```

This seems to be because you use _usize_ throughout the file. According to the docs _usize_ is: 
> A pointer-sized unsigned integer type.

So on 32-bit systems the size of it will be 4 bytes. I think you should use _u64_ instead.

**Comment by drevilt** [comment]
thank you for the quick patch.

it compiles now but unfortunatley i still get an error when i try to run a program with an inline dyon script:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /buildslave/rust-buildbot/slave/nightly-dist-rustc-cross-host-linux/build/src/libcore/option.rs:325
stack backtrace:
   1: 0x54e11ce3 - std::sys::backtrace::tracing::imp::write::hae41634db4b63afe
   2: 0x54e15fc3 - std::panicking::default_hook::{{closure}}::hf5c95509b45e94d3
   3: 0x54e14b3b - std::panicking::default_hook::h6d65552e1d4a38dc
   4: 0x54e1524f - std::panicking::rust_panic_with_hook::hbcdd76ca45e6ae3d
   5: 0x54e1510b - std::panicking::begin_panic::h5ff54e8bc0fe854f
   6: 0x54e15047 - std::panicking::begin_panic_fmt::h1952741b33ce8f6d
   7: 0x54e14fdb - rust_begin_unwind
   8: 0x54e37c23 - core::panicking::panic_fmt::h8ed436dba3f67852
   9: 0x54e37b77 - core::panicking::panic::h3275d95fad98f205
  10: 0x54b380db - <core::option::Option<T>>::unwrap::hfcede90746096e2a
                at /buildslave/rust-buildbot/slave/nightly-dist-rustc-cross-host-linux/build/src/libcore/macros.rs:21
  11: 0x54cf85cf - dyon::Module::error::h4758118292a2cfb8
                at /.../dyon-0.9.1/src/lib.rs:268
  12: 0x54c0b31b - dyon::runtime::Runtime::run::heccac292c6e07f2b
                at /.../dyon-0.9.1/src/runtime.rs:555
  13: 0x54b15b0b - dyon_test::main::h81487bbebbbf0317
                at /.../dyon_test/src/main.rs:14
  14: 0x54e19f43 - __rust_maybe_catch_panic
  15: 0x54e14293 - std::rt::lang_start::h6d20aa8156b6f2f5
  16: 0x54b15efb - main
  17: 0x76e83631 - __libc_start_main
```

I dont fully understand the code but i think this is because in `link.rs` line 81 and line 101 you still transmute to a _usize_ which means that 4 bytes of the 8 ( because you cast to u64 later )  will be zero. If you are storing pointers in there , the pointers will get corrupted.

https://github.com/PistonDevelopers/dyon/blob/5fdddcc96fd9b3a87be67823b74481ac17fe16a2/src/link.rs#L101

this is my test program:
```rust
#[macro_use]
extern crate dyon;
use std::sync::Arc;
use dyon::*;

fn main() {
    let mut dyon_runtime = Runtime::new();
    let mut dyon_module = Module::new();
    dyon_module.add(Arc::new("say_hello".into()), say_hello, Dfn {
        lts: vec![],
        tys: vec![],
        ret: Type::Void
    });
    if error(dyon_runtime.run(&dyon_module)) {
        return
    }
}

dyon_fn!{
fn say_hello() {
    println!("hi!");
}}

```


You should be able to reproduce it locally if you build it to a 32-bit program using `cargo build --target i686-unknown-linux-gnu` or something similar. All unittests run without errors. Or is my test program just wrong ?

**Comment by bvssvni** [comment]
It seems you forgot to load a module. See https://github.com/PistonDevelopers/dyon/blob/master/examples/functions.rs#L59

**Comment by drevilt** [comment]
Oh i see. I tried the load function and it works fine now . Thank you! 
I thought the `dyon_fn!` was enought to make it run.
